name: Publish

on:
  push:
    branches:
      - latest

jobs:
  publish:
    name: Publish the package
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.AUTH_TOKEN }}" > .npmrc

      - name: Installation
        run: docker-compose run --rm --user root -T npm install

      - name: Build
        run: docker-compose run --rm --user root -T npm run build

      - name: Publish
        run: 'docker-compose run --rm --user root -T npm publish --access public || true'
